version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspace:cached
      - node_modules:/workspace/node_modules
      - api_node_modules:/workspace/api/node_modules
      - frontend_node_modules:/workspace/frontend/node_modules
    command: sleep infinity
    ports:
      - '8080:8080' # API
      - '5173:5173' # Vite
    environment:
      - NODE_ENV=development

volumes:
  node_modules:
  api_node_modules:
  frontend_node_modules:
